version: '3.9'

services:
  database:
    build:
      context: ./database
    ports:
      - '5432:5432'
    env_file:
      - db.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${PGRES_USERNAME} -d ${POSTGRES_DB}'"]
      interval: 30s
      timeout: 30s
      retries: 5

  reverse-geocoding:
    container_name: reverse-geocode
    image: mediagis/nominatim:4.0
    restart: always
    ports:
        - "8080:8080"
    env_file:
        - revgeocode.env
    volumes:
        - ./geocode-data/:/revgeocode/data
        - ./nominatim-data/postgresql:/var/lib/postgresql/12/main
    shm_size: 1gb

  routing-engine:
    container_name: routing-engine
    image: routing-engine:latest
    ports:
      - '8989:8989'
    command: --url https://download.geofabrik.de/north-america/canada/ontario-latest.osm.pbf --host 0.0.0.0

  message-broker:
    build:
      context: ./rabbitmq
    container_name: demo-broker
    ports:
      - "5672:5672"  # rabbitmq port
      - "15672:15672"  # management plugin port

  simulator:
    container_name: simulator
    image: mosteligible/sim-service:0.0.0
    ports:
      - '5000:5000'
    env_file:
      - simulator.env
    depends_on:
      - reverse-geocoding
      - database
      - routing-engine
    healthcheck:
      test: curl --fail http://localhost:5000/status || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
