version: '3.9'

services:
  database:
    build:
      context: ./database
    ports:
      - '3306:3306'
    env_file:
      - db.env

  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - database
    env_file:
      - db.env
